@host = http://localhost:5281

# ⚠️ IMPORTANTE: reemplazar accessToken por uno válido antes de hacer la prueba
# ⚠️ IMPORTANT: reemplace accessToken to a valid one before doing the test
@accessToken = {{accessToken}}

### Create a new OrderItem By UserId

POST {{host}}/api/orderItems/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###

