@host = http://localhost:5281

# ⚠️ IMPORTANTE: reemplazar accessToken por uno válido antes de hacer la prueba
# ⚠️ IMPORTANT: reemplace accessToken to a valid one before doing the test
@accessToken = {{accessToken}}

### Get cart by user id

GET {{host}}/api/carts/1
Accept: application/json
Authorization: Bearer {{accessToken}}

###

