@host = http://localhost:5281

# ⚠️ IMPORTANTE: reemplazar accessToken por uno válido antes de hacer la prueba
# ⚠️ IMPORTANT: reemplace accessToken to a valid one before doing the test
@accessToken = {{accessToken}}

### Get all users

GET {{host}}/api/users
Accept: application/json
Authorization: Bearer {{accessToken}}

###

### Get user by id

GET {{host}}/api/users/11
Accept: application/json
Authorization: Bearer {{accessToken}}

###

### Create a new User

POST {{host}}/api/users
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "firstName": "Carlos",
    "lastName" : "Diaz",
    "userName" : "CDi32",
    "email" : "carlos@mail.com",
    "password" : "carlos123",
    "description" : "Hola a todos!",
    "country" : "Argentina",
    "role" : "Client",
    "image" : "https://randomuser.me/api/portraits/men/76.jpg"
}

###

### Update existing User

PUT {{host}}/api/users/11
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "id" : 11,
    "firstName": "Juan",
    "lastName" : "Rodriguez",
    "userName" : "Juancho16",
    "email" : "juan@mail.com",
    "password" : "juan123456",
    "description": "hola",
    "country" : "Argentina",
    "role" : "Client",
    "image" : "https://randomuser.me/api/portraits/men/75.jpg"
}

###

### Delete User

DELETE {{host}}/api/users/1
Authorization: Bearer {{accessToken}}

###

### Reset DB to default

POST {{host}}/api/users/reset-db
Authorization: Bearer {{accessToken}}

###
